# Change these first
owner: raidensakura # Your GitHub organization or username, where this repository lives
repo: shogun-status # The name of this repository
user-agent: raidensakura

sites:
  - name: Website
    url: https://project-mei.xyz
    icon: https://project-mei.xyz/images/logo.png
  - name: VPS Dashboard
    url: https://home.project-mei.xyz
  - name: Shogun Bot
    url: https://shogun.project-mei.xyz
  - name: Shogun Dashboard
    url: https://dash.project-mei.xyz
  - name: Archi Steam Farm
    url: https://asf.project-mei.xyz
  - name: Grafana
    url: https://graph.project-mei.xyz
  - name: InfluxDB
    url: https://influxdb.project-mei.xyz
      
assignees:
  - raidensakura

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  cname: status.project-mei.xyz
  favicon: https://project-mei.xyz/images/logo.png
  logoUrl: https://project-mei.xyz/images/logo.png
  logoHref: https://project-mei.xyz
  name: Project MEI Status
  theme: night
  introTitle: Project MEI Status
  introMessage: Keep track of services hosted by Raiden here.
  navbar:
    - title: Home
      href: https://project-mei.xyz
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
