# Change these first
owner: raidensakura # Your GitHub organization or username, where this repository lives
repo: shogun-status # The name of this repository
user-agent: raidensakura

sites:
    # Dashboards and main sites
  - name: Main Website
    url: https://project-mei.xyz
    icon: https://project-mei.xyz/images/logo.png
  - name: Home Dashboard
    url: https://home.project-mei.xyz
    icon: https://home.project-mei.xyz/imgs/logo.png
  - name: Portainer
    url: https://portainer.project-mei.xyz/
    icon: https://portainer.project-mei.xyz/2dcfc527d067d4ae3424.png
    # Shogun bot
  - name: Shogun Bot
    url: https://shogunbot.project-mei.xyz
    icon: https://project-mei.xyz/images/shogun-logo.png
  - name: Shogun Dashboard
    url: https://dash.project-mei.xyz
    icon: https://project-mei.xyz/images/shogun-logo.png
    # Grafana-related
  - name: Grafana
    url: https://graph.project-mei.xyz
    icon: https://graph.project-mei.xyz/public/img/grafana_icon.svg
  - name: InfluxDB
    url: https://influxdb.project-mei.xyz
    icon: https://asf.project-mei.xyz/images/logo.png
    # Discord Modmails
  - name: Logviewer/Makoto
    url: https://makoto.project-mei.xyz/
    icon: https://makoto.project-mei.xyz/static/favicon.ico
  - name: Logviewer/Teriri
    url: https://teriri.project-mei.xyz/
    icon: https://teriri.project-mei.xyz/static/favicon.ico
    # Misc stuff
  - name: Archi Steam Farm
    url: https://asf.project-mei.xyz
    icon: https://asf.project-mei.xyz/images/logo.png
  - name: TeamSpeak 3 Server
    icon: https://files.catbox.moe/fl9kv8.jpg
    check: "tcp-ping"
    url: $SHOGUN_IP
    port: 10011
      
assignees:
  - raidensakura

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  cname: status.project-mei.xyz
  favicon: https://project-mei.xyz/images/logo.png
  logoUrl: https://project-mei.xyz/images/logo.png
  logoHref: https://project-mei.xyz
  name: Project MEI Status
  theme: light
  introTitle: Project MEI Status
  introMessage: Keep track of services hosted by Raiden here.
  navbar:
    - title: Home
      href: https://project-mei.xyz
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
runner: [self-hosted]

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
