# Change these first
owner: Project-MEI # Your GitHub organization or username, where this repository lives
repo: statuspage
user-agent: raidensakura

sites:
  - name: Main VPS
    icon: https://old.project-mei.xyz/images/shogun-logo.png
    check: "tcp-ping"
    url: $VPS_IP
    port: $VPS_PORT
  - name: Main Monitor
    icon: https://old.project-mei.xyz/images/logo.png
    check: "tcp-ping"
    url: status.project-mei.xyz
    port: 80
      
assignees:
  - raidensakura

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /statuspage
  cname: uptime.project-mei.xyz
  favicon: https://old.project-mei.xyz/images/logo.png
  logoUrl: https://old.project-mei.xyz/images/logo.png
  logoHref: https://uptime.project-mei.xyz
  name: Project MEI Uptime
  theme: night
  introTitle: Project MEI Monitor
  introMessage: A status page powered by Upptime, hosted on GitHub Pages. This page is a backup of the main monitor.
  navbar:
    - title: Home
      href: https://project-mei.xyz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://dsc.gg/transience
    - title: Main Monitor
      href: https://status.project-mei.xyz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
